### Objetivo

* Comprobar la homologación de los datos (ids iguales para los 3 archivos provistos)
* Realizar test para determinar si una pregunta es basal o no basal de forma estadística. Esto es encontrar algún umbral de valores nulos que indiquen que una pregunta se debería considerar basal o no basal. Para ello, se inicia con las preguntas que corresponden a la depresión, codificadas como las que inician con 'pmd'

In [2]:
import pandas as pd 
import matplotlib.pyplot as plt
import plotly.express as px

### Carga de los 3 datasets (Previamente innominados)

In [4]:
df_base_de_datos = pd.read_excel(r"C:\Users\Lan_1\Documents\VictorL_TesinaMACI\VictorL_TesinaMACI\Python\data\base datos proyecto infante juvenil 4 OCTUBRE 2010.xlsx")
df_sintomas_disc = pd.read_excel(r"C:\Users\Lan_1\Documents\VictorL_TesinaMACI\VictorL_TesinaMACI\Python\data\Sintomas_disc_Infante_Juvenil_n=1558.xlsx")
df_sub_umbrales  = pd.read_excel(r"C:\Users\Lan_1\Documents\VictorL_TesinaMACI\VictorL_TesinaMACI\Python\data\sub_umbrales_jovenes_infantes.xlsx")

### Revisión de tamaños de los datasets

Esto se hace principalmente para ver la integridad de los datos (asegurarse que tengan el mismo número de filas y que estas corresponden a los mismos sujetos)

In [6]:
print(df_base_de_datos.shape)
print(df_sintomas_disc.shape)
print(df_sub_umbrales.shape)

(1558, 830)
(1558, 3503)
(1558, 261)

Se definen las columnas de cada dataset

In [8]:
cols_base_de_datos = (df_base_de_datos.columns)
cols_sintomas_disc = (df_sintomas_disc.columns)
cols_sub_umbrales = (df_sub_umbrales.columns)

print(cols_base_de_datos)
print('-'*50)
print(cols_sintomas_disc)
print('-'*50)
print(cols_sub_umbrales)

Index(['inum', 'estrato', 'psu', 'peso_std_provincia_ajustado',
       'peso_ajustado_final', 'sex1', 'ed1', 'esc1', 'eciv1', 'act1',
       ...
       'NPERSON', 'Nin_Inf', 'ICD_1', 'dx_s1', 'ICD_2', 'ICD_3', 'ICDi_1',
       'ICDi_2', 'ICDi_3', 'grupox'],
      dtype='object', length=830)
--------------------------------------------------
Index(['id', 'huid', 'pad001', 'pad001a', 'pad001b', 'pad001c', 'pad001d',
       'pad002', 'pad002a', 'pad002b',
       ...
       'pwq019', 'pwq020', 'pwq021', 'pwq022', 'pwq022a', 'pwq023', 'pwq023a',
       'pwq024', 'pwq025', 'pwq026'],
      dtype='object', length=3503)
--------------------------------------------------
Index(['inum', 'ed1', 'padcrt1y', 'padcrt2y', 'padcrt1m', 'padcrt2m',
       'padcrt3y', 'padcrt3m', 'padsymp', 'patsymp',
       ...
       'pszsubtimb', 'pszsubtimc', 'pszsubtimd', 'yszcrit', 'yszsymp',
       'yszsubt', 'yszsubtima', 'yszsubtimb', 'yszsubtimc', 'yszsubtimd'],
      dtype='object', length=261)

Se definen los identificadores de cada dataset

In [10]:
print(df_base_de_datos['inum'])
print(df_sintomas_disc['id'])
print(df_sintomas_disc['huid'])
print(df_sub_umbrales['inum'])

0          1
1          2
2          3
3          4
4          5
        ...
1553    1875
1554    1876
1555    1877
1556    1879
1557    1880
Name: inum, Length: 1558, dtype: int64
0          1
1          2
2          3
3          4
4          5
        ...
1553    1875
1554    1876
1555    1877
1556    1879
1557    1880
Name: id, Length: 1558, dtype: int64
0        1
1        2
2        3
3        4
4        5
        ..
1553    75
1554    76
1555    77
1556    79
1557    80
Name: huid, Length: 1558, dtype: int64
0          1
1          2
2          3
3          4
4          5
        ...
1553    1875
1554    1876
1555    1877
1556    1879
1557    1880
Name: inum, Length: 1558, dtype: int64

A simple vista, sí existe integridad en cuanto a ids homologados entre los datasets.

### Revisión de homologación

Se revisa si entre los 3 datasets, ID, INUM Y HUID son iguales

In [13]:
#Revisión de Integridad de identificadores

print(sorted(list(df_base_de_datos['inum'])) == sorted(list(df_sub_umbrales['inum'])))
print(sorted(list(df_base_de_datos['inum'])) == sorted(list(df_sintomas_disc['id'])))
print(sorted(list(df_base_de_datos['inum'])) == sorted(list(df_sintomas_disc['huid'])))

True
True
False

Huid no es igual a ID e INUM

Se comprueba además que huid ni siquiera contiene los mismos valores únicos; a diferencia de ID e INUM cuyos valores sí son úncos (valores únicos = número de filas = 1558)

In [16]:
#Revisión de valores únicos para id y huid

unique_id = (df_base_de_datos['inum'].unique())
unique_huid = (df_sintomas_disc['huid'].unique())

print(len(list(unique_id)))
print(len(list(unique_huid)))

1558
100

### Preguntas Basales y No Basales

Por ahora sólo nos interesa ver si las preguntas relacionadas a Depresión son basales o no. Para ello se revisa el dataset de síntomas

In [19]:
depression_cols_sintomas_disc = [i for i in cols_sintomas_disc if i.startswith('pmd')]
depression_cols_sub_umbrales = [i for i in cols_sub_umbrales if i.startswith('pmd')]

In [20]:
depression_df_sintomas_disc = df_sintomas_disc[list(depression_cols_sintomas_disc)]
depression_df_sub_umbrales = df_sub_umbrales[list(depression_cols_sub_umbrales)]

In [21]:
#Información general del set de preguntas sobre depresión.

display(depression_df_sintomas_disc.info())
display(depression_df_sintomas_disc.head())
display(depression_df_sintomas_disc.describe())
display(depression_df_sintomas_disc.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1558 entries, 0 to 1557
Columns: 240 entries, pmd001 to pmd060c
dtypes: float64(240)
memory usage: 2.9 MB

None

,pmd001,pmd001a,pmd001b,pmd001c,pmd001d,pmd001e,pmd001f,pmd002,pmd002a,pmd002b,...,pmd057,pmd057a,pmd058,pmd058a,pmd059,pmd059a,pmd060,pmd060a,pmd060b,pmd060c
0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,0.0,NaN,NaN,NaN,NaN,NaN,2.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2.0,0.0,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,pmd001,pmd001a,pmd001b,pmd001c,pmd001d,pmd001e,pmd001f,pmd002,pmd002a,pmd002b,...,pmd057,pmd057a,pmd058,pmd058a,pmd059,pmd059a,pmd060,pmd060a,pmd060b,pmd060c
count,1556.000000,667.000000,316.000000,316.000000,232.000000,162.000000,162.000000,1556.000000,352.000000,179.000000,...,7.000000,5.0,7.0,7.0,0.0,0.0,99.000000,49.000000,49.000000,13.000000
mean,0.857326,0.947526,1.297468,1.468354,1.396552,1.586420,0.814815,0.452442,1.042614,1.340782,...,1.285714,2.0,0.0,0.0,NaN,NaN,0.989899,1.346939,0.530612,1.384615
std,0.990088,0.999372,0.956246,0.884942,0.919997,1.025423,0.985751,0.837037,1.086515,0.942779,...,0.951190,1.0,0.0,0.0,NaN,NaN,1.005038,0.947607,0.892143,0.960769
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.0,0.0,0.0,NaN,NaN,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,...,0.500000,1.0,0.0,0.0,NaN,NaN,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,2.000000,2.000000,2.000000,2.000000,0.000000,0.000000,2.000000,2.000000,...,2.000000,2.0,0.0,0.0,NaN,NaN,0.000000,2.000000,0.000000,2.000000
75%,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,0.000000,2.000000,2.000000,...,2.000000,3.0,0.0,0.0,NaN,NaN,2.000000,2.000000,2.000000,2.000000
max,2.000000,2.000000,2.000000,2.000000,2.000000,9.000000,2.000000,2.000000,9.000000,2.000000,...,2.000000,3.0,0.0,0.0,NaN,NaN,2.000000,2.000000,2.000000,2.000000

pmd001        2
pmd001a     891
pmd001b    1242
pmd001c    1242
pmd001d    1326
           ...
pmd059a    1558
pmd060     1459
pmd060a    1509
pmd060b    1509
pmd060c    1545
Length: 240, dtype: int64

### Conteo de nulos por pregunta

Me interesa trabajar con este subconjunto de preguntas porque están ya identificadas en varios archivos y puedo comprobar 'manualmente' ciertos aspectos relacionados a valores perdidos.

In [23]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

display(depression_df_sintomas_disc.isnull().sum())

pmd001         2
pmd001a      891
pmd001b     1242
pmd001c     1242
pmd001d     1326
pmd001e     1396
pmd001f     1396
pmd002         2
pmd002a     1206
pmd002b     1379
pmd002c     1438
pmd003         2
pmd003a      802
pmd003b     1277
pmd003c     1277
pmd003d     1367
pmd003e     1434
pmdn01       477
pmdn02         2
pmd004         2
pmd004a     1207
pmd004b     1446
pmd004c     1286
pmd004d     1474
pmd004e     1286
pmd005         2
pmd005a     1445
pmd005b     1480
pmd005c     1163
pmd006         2
pmd006a     1259
pmd006b     1466
pmd006c     1259
pmd007         2
pmd007a     1435
pmd007b     1504
pmd007c     1118
pmdn03a        2
pmdn03b        2
pmd008         2
pmd008a     1027
pmd008b     1384
pmd008c     1436
pmd008d     1027
pmd009         2
pmd009a     1442
pmd009b     1489
pmd009c     1143
pmdn04a        2
pmdn04b        2
pmd010         2
pmd010a      630
pmd010b     1465
pmd010c     1491
pmd010d     1317
pmd011         2
pmd011a      739
pmd011b     1169
pmd011c     1437
pmd011d     1501
pmd011e     1169
pmdn05a        2
pmdn05b        2
pmd012         2
pmd012a     1411
pmd012b     1429
pmd012c     1121
pmd013         2
pmd013a     1257
pmd013b     1448
pmd013c     1485
pmd013d     1257
pmdn06a        2
pmdn06b        2
pmd014         2
pmd014a     1476
pmd014b     1496
pmd014c     1334
pmd015         2
pmd015a     1175
pmd015b     1423
pmd015c     1455
pmd015d     1175
pmd016         2
pmd016a     1107
pmd016b     1408
pmd016c     1438
pmd016d     1107
pmdn07a        2
pmdn07b        2
pmd017         2
pmd017a     1444
pmd017b     1469
pmd017c     1223
pmd018         2
pmd018a      850
pmd018b     1378
pmd018c     1430
pmd018d      850
pmd019         2
pmd019a     1060
pmd019b     1420
pmd019c     1457
pmd019d     1060
pmdn08a        2
pmdn08b        2
pmd020         2
pmd020a     1086
pmd020b     1405
pmd020c     1468
pmd020d     1086
pmd021         2
pmd021a     1453
pmd021b     1453
pmd021c     1510
pmd021d     1453
pmd021e     1543
pmd021f     1543
pmd022         2
pmd022a     1466
pmd022b     1466
pmd022c     1518
pmd022d     1518
pmd022e     1518
pmd022f     1533
pmd022g     1518
pmdn09a        2
pmdn09b        2
pmdn09c        2
pmdn10         2
pmd023y     1342
pmd023z     1558
pmd023a     1462
pmd023b     1426
pmd023c     1459
pmd023dy    1489
pmd023dz    1558
pmd023e     1519
pmd024      1342
pmd024a     1513
pmd024b     1513
pmd024bm    1513
pmd024by    1513
pmd024c     1513
pmd024d     1542
pmd024e     1552
pmd024f     1555
pmd025      1507
pmd025a     1515
pmd025b     1542
pmd025c     1548
pmd025d     1548
pmd025e     1548
pmd025f     1548
pmd025g     1556
pmd025h     1552
pmd025i     1554
pmd025j     1554
pmd025k     1554
pmd025l     1554
pmd025m     1554
pmd026      1342
pmd026a     1479
pmd027      1342
pmd027a     1476
pmd028      1342
pmd028a     1477
pmd029      1347
pmd029a     1436
pmd030      1347
pmd030a     1503
pmd031      1342
pmd031a     1406
pmd032      1342
pmd032a     1372
pmd033      1523
pmd033a     1528
pmd034      1342
pmd034ay    1509
pmd034az    1558
pmd035        87
pmd035a     1301
pmd035b     1521
pmd035c     1536
pmd035d     1521
pmd035e     1521
pmd035f     1521
pmd036       109
pmd036a     1259
pmd036b     1510
pmd036c     1539
pmd036d     1510
pmd036e     1510
pmd037      1517
pmd037a     1528
pmd038      1517
pmd038a     1539
pmd039      1517
pmd040      1517
pmd041      1517
pmd041a     1551
pmd042      1517
pmd042a     1529
pmd043      1517
pmd044      1517
pmd045      1517
pmd046      1517
pmd047      1517
pmd048      1517
pmd049      1517
pmd050      1520
pmd050a     1524
pmd051y     1544
pmd051z     1558
pmd051a     1553
pmd051b     1549
pmd051c     1555
pmd051dy    1556
pmd051dz    1558
pmd051e     1556
pmd052      1551
pmd052a     1553
pmd053      1551
pmd053a     1556
pmd054      1551
pmd054a     1558
pmd055      1551
pmd055a     1552
pmd056      1551
pmd056a     1555
pmd057      1551
pmd057a     1553
pmd058      1551
pmd058a     1551
pmd059      1558
pmd059a     1558
pmd060      1459
pmd060a     1509
pmd060b     1509
pmd060c     1545
dtype: int64

Es sencillo notar que las preguntas no terminadas en letras son consideradas basales dentro del DISC y coinciden con los valores perdidos por el sistema según el archivo 'Libro codigos Sintomas Infante Juvenil N=1558.doc' provisto. 

Por ejemplo, la pregunta 35 o pmd035, que en el cuestionario 'Dd-21.wpd' es 'Durante el último año–es decir, desde [[MENCIONE SUCESO]/[MENCIONE MES ACTUAL] del año pasado] – ¿hubo una  época en que te sentiste triste o deprimido(a) gran parte del tiempo (muchas veces)?' y en el libro de código es 'Seemed sad or depressed a lot of the time in past year', coincide en código y valores nulos perdidos por el sistema (87) entre el libro de código y los datos de 'Sintomas_disc_Infante_Juvenil_n=1558.xlsx'. Así mismo, hay conexión en cuanto a intención y sintaxis entre el libro de código en inglés y el cuestionario en español, así que es fácil ver que es efectivamente una pregunta que abre hacia otras 5 preguntas no basales (pmd035a-f).

Si esto es cierto para el resto de preguntas, y ya existen cantidades documentadas de valores perdidos, analiizar si una pregunta es basal o no basal a partir de umbrales estadísticos no es del todo válida, ya que existen preguntas cuyo porcentaje de pérdida por el sistema es muy alta, por ejemplo, la pregunta pmd056 ('Being sad/depressed/grouchy/irritable made teachers/bosses annoyed') tiene 1551 valores perdidos (nulos) y sería marcada como no basal.

De todas formas, este Notebook comprueba que existe homologación entre los datos de los 3 datasets